# Generated by Django 4.1.2 on 2023-02-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='product',
        ),
        migrations.AddField(
            model_name='products',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='product.images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'ELECTRONICS'), ('fASHION', 'FASHION'), ('SPORTS', 'SPORTS'), ('HOME_DECOR', 'HOME_DECOR'), ('GADGETS', 'GADGETS')], max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
